### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by hoechenberger** [hoechenberger/dipoles_demo#26]
- [ ] Add measurement units to colorbars
- [ ] Fix signal magnitudes in colorbars
- [ ] Gracefully handle the case that dipole is placed outside of the brain (currently raises an exception)
- [ ] **S P E E D** 🐢
- [ ] Allow users to adjust dipole amplitude
